import { placeholder } from "i18n-js";
import colors from "../config/colors";

export const lightColors = {
  primary: colors.blue,
  secondary: colors.secondary,
  text: colors.black,
  background: colors.light,
  assitantbg: colors.white,
  fileBackground: colors.lightGrey,
  border: colors.lightGrey,
  icon: colors.black,
  danger: colors.danger,
  deleteRed: colors.deleteRed,
  dark: colors.dark,
  grey: colors.grey,
  lightGrey: colors.lightGrey,
  blue: colors.blue,
  medium: colors.medium,
  light: colors.light,
  white: colors.white,
  button_blue: colors.niceBlue,
  placeholder: colors.placeholder,
  docPicker: colors.light,
  text_input: colors.text_input_light,
  assistant_bubble: colors.light,
  assistant_text: colors.dark,
};

export const darkColors = {
  primary: colors.dark_blue,
  secondary: colors.secondary,
  text: colors.white,
  background: colors.dark_light,
  fileBackground: colors.grey2,
  border: colors.dark,
  icon: colors.white,
  danger: colors.danger,
  deleteRed: colors.deleteRed,
  dark: colors.dark_dark,
  grey: colors.grey,
  lightGrey: colors.lightGrey,
  blue: colors.dark_blue,
  medium: colors.medium,
  light: colors.dark_light,
  white: colors.dark_white,
  button_blue: colors.button_dark_blue,
  placeholder: colors.placeholder,
  docPicker: colors.docPicker,
  assistangbg: colors.grey2,
  text_input: colors.text_input_dark,
  assistant_bubble: colors.dark_bubble,
  assistant_text: colors.dark_dark,
};
