// const en = {
//     Chat: "",
//     Assistants: "",
//     Setting: "",
//     edit: "",
//     newAssistant: "",
//     choosingPhotoForAssistant: "",
//     choosingNameForAssistant: "",
//     enterName: "",
//     giveAssistantInstruction: "",
//     enterInstructions: "",
//     next: "",
//     chooseModel: "",
//     selectModel: "",
//     fileUploadReq: "",
//     fileUpload: "",
//     saveAssistant: "",
//     done: "",
//     delete: "",
//     save: "",
//     enterAPIKey: "",
//     Languages: "",
//     selectLang: "",
//     TOS: "",
//     PriPol: "",
//     aboutUs: "",
//   };

const localizations = {
  en: {
    Chat: "Chat",
    Assistants: "Assistants",
    Setting: "Setting",
    edit: "edit",
    newAssistant: "New Assistant",
    choosingPhotoForAssistant: "You can choose a photo for your assistant",
    choosingNameForAssistant: "Choose a name for your assistant",
    enterName: "Enter name",
    giveAssistantInstruction:
      "Give your assistant instructions on how it should behave",
    enterInstructions: "Enter instructions",
    next: "next",
    chooseModel: "Choose a model for your assistant",
    selectModel: "Select a model",
    fileUploadReq:
      "If you want to upload files for the knowledge base you need to choose gpt 4 turbo ",
    fileUpload: "Upload pdf, word and text files to your assistant",
    saveAssistant: "Save assistant",
    done: "Done",
    delete: "Delete",
    save: "Save",
    apikey: "OpenAI API Key",
    enterAPIKey: "Enter API key",
    Languages: "Languages",
    selectLang: "Select Languages",
    TC: "Terms and Conditions",
    PriPol: "Privacy policy",
    aboutUs: "About us",
    noAssistants: "No assistants available. Please add a new assistant",
  },

  fa: {
    Chat: "گفتگو",
    Assistants: "راهنما",
    Setting: "تنظیمات",
    edit: "ویرایش",
    newAssistant: "راهنمای جدید",
    choosingPhotoForAssistant: "عکس راهنما",
    choosingNameForAssistant: "نام راهنما",
    enterName: "نام راهنما را وارد کنید",
    giveAssistantInstruction: "با نوشتن دستورات، جواب های دقیقتری بگیرید",
    enterInstructions: "دستورات را وارد کنید",
    next: "بعدی",
    chooseModel: "مدل هوش مصنوعی را انتخاب کنید",
    selectModel: "انتخاب مدل",
    fileUploadReq:
      "اگر میخواهید فایل آپلود بکنید، مدل پایه gpt 4 turbo را انتخاب کنید",
    fileUpload: "فایل pdf یا word و یا txt آپلود کنید",
    saveAssistant: "ذخیره راهنما",
    done: "تمام",
    delete: "حذف",
    save: "ذخیره",
    apikey: "کلید API",
    enterAPIKey: "کلید API را وارد کنید",
    Languages: "زبان",
    selectLang: "انتخاب زبان",
    TC: "شرایط و ضوابط",
    PriPol: "قوانین و مقررات",
    aboutUs: "درباره ما",
    noAssistants: "راهنمایی وجود ندارد. لطفا یک راهنما بسازید",
  },
};

export default localizations;
